<?php

// Define debug vars
define('SWAB_ADVICE_GROUP_DEBUG', TRUE);

/**
 * Implements hook_form_alter().
 */
function swab_advice_group_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'advice_group_node_form':
      $form = swab_advice_group_change_form($form, $form_state);
      break;
  }
}

function swab_advice_group_change_form($form, $form_state) {
  form_load_include($form_state, 'inc', 'swab_advice_group', 'swab_advice_group_forms');

  $tree = array();
  if(isset($form_state['node']->nid)) {
    // TODO: Do something with the exisiting node if available
  }

  $form['#submit'][] = 'swab_advice_group_form_submit_handler';

  $form['adv_fieldset'] = array(
      '#type' => 'fieldset',
      '#prefix' => '<div id="adv_group_forms">',
      '#suffix' => '</div>',
      '#title' => check_plain($form['field_advcg_advc']['und']['#title']),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#weight' => $form['field_advcg_advc']['#weight'],
      '#description' => check_plain($form['field_advcg_advc']['und']['#description']),
      '#tree' => TRUE,
  );
  // This variable will hold the current number of subforms
  if (empty($form_state['swab_advice_group_form_index'])) {
    $form_state['swab_advice_group_form_index'] = array(0);
  }
  foreach ($form_state['swab_advice_group_form_index'] AS $index) {
    $form['adv_fieldset']['adv_group_form'][$index] = swab_advice_group_create_form($index);
  }
  if (!SWAB_ADVICE_GROUP_DEBUG) {
    $form['field_advcg_advc']['#access'] = FALSE;
  }
  return $form;
}

function swab_advice_group_create_form($index) {
  $age = swab_advice_group_field_get_items('field_advc_age_ref', 'advice');
  $weight = swab_advice_group_field_get_items('field_advc_weight_ref', 'advice');

  $form = array();

  $form['advice_group_' . $index] = array(
    '#type' => 'fieldset',
    '#attributes' => array(
    'class' => array('advice_group_fieldset')
    )
  );

  $form['advice_group_' . $index]['advice_group_' . $index] = array(
      '#type' => 'container',
      '#attributes' => array(
          'class' => array('advices_table')
      )
  );
  // header row
  $form['advice_group_' . $index]['advice_group_table_' . $index]['advice_group_table_header_' . $index] = array(
      '#type' => 'container',
      '#attributes' => array(
          'class' => array('advice_group_table_header', 'advice_group_table_row')
      )
  );
  $header = array(t('Patient Age'), t('Patient Weight'), t('Indications'), t('Remarks'), t('Dosage Schema'), t('Score'), '');
  // header fields
  $form['advice_group_' . $index]['advice_group_table_' . $index]['advice_group_table_' . $index]['adv_pa_' . $index] = array(
      '#type' => 'item',
      '#markup' => t('Patient Age'),
  );
  $form['advice_group_' . $index]['advice_group_table_' . $index]['advice_group_table_' . $index]['adv_w_' . $index] = array(
      '#type' => 'item',
      '#markup' => t('Patient Weight'),
  );
  $form['advice_group_' . $index]['advice_group_table_' . $index]['advice_group_table_' . $index]['adv_ind_' . $index] = array(
      '#type' => 'item',
      '#markup' => t('Indications'),
  );
  $form['advice_group_' . $index]['advice_group_table_' . $index]['advice_group_table_' . $index]['adv_rem_' . $index] = array(
      '#type' => 'item',
      '#markup' => t('Remarks'),
  );
  $form['advice_group_' . $index]['advice_group_table_' . $index]['advice_group_table_' . $index]['adv_dos_' . $index] = array(
      '#type' => 'item',
      '#markup' => t('Dosage Schema'),
  );
  $form['advice_group_' . $index]['advice_group_table_' . $index]['advice_group_table_' . $index]['adv_sc_' . $index] = array(
      '#type' => 'item',
      '#markup' => t('Score'),
  );

  // $form['advices_' . $index]['adv_age'] = array(
    // '#type' => 'select',
    // '#description' => check_plain($age['description']),
    // '#options' => $age['values'],
    // '#required' => $age['required'],
    // '#default_value' => '', // TODO: Add default value if available
  // );
  // $form['advices_' . $index]['adv_weight'] = array(
    // '#type' => 'select',
    // '#description' => check_plain($weight['description']),
    // '#options' => $weight['values'],
    // '#required' => $weight['required'],
    // '#default_value' => '', // TODO: Add default value if available
  // );
  // $form['advices_' . $index]['adv_indication'] = array(
    // '#markup' => 'Indication placeholder',
  // );
  // $form['advices_' . $index]['adv_remarks'] = array(
    // '#markup' => 'Remarks placeholder',
  // );
  // $form['advices_' . $index]['adv_dosage'] = array(
    // '#markup' => 'Dosage placeholder',
  // );
  // $form['advices_' . $index]['adv_score'] = array(
    // '#markup' => 'Score placeholder',
  // );
  // $form['advices_' . $index]['weight'] = array(
    // '#type' => 'weight',
    // '#title' => t('Weight'),
    // '#default_value' => 0,
    // '#delta' => 10,
    // '#title-display' => 'invisible',
  // );

  return $form;
}

function swab_advice_group_form_submit_handler($form, &$form_state) {

}
